### ISSUE TITLE
Feature: Browse questions for interview instead of serving random question for a difficulty.  

### ISSUE THREAD

**Issue by Maker-Mark** [HackerPen/roadmap#6]
It's not very helpful to get a random question based on "difficulty". Many times, I have a question in mind I want to give (generally I can give better feedback on a question I'm familiar with). 
It could also be nice to generate a question based on topics too, or just allow the user to search or see results based off of difficulty + pattern + topic selection.

**Comment by marshallshen** [comment]
Great suggestion! This is something we should definitely add, will put it on the roadmap, thanks!
